(use-modules (guix gexp)
             (guix packages)
             (guix build-system trivial)
             (gnu packages base)
             (gnu packages node)
             (gnu packages java)
             (gnu packages python-web)
             (nongnu packages clojure))

(package
 (name "name")
 (version "0.0.1")
 (source (local-file "."))
 (build-system trivial-build-system)
 (native-inputs
  `(("make" ,gnu-make)
    ("node" ,node-lts)
    ("openjdk" ,openjdk16 "jdk")
    ("clojure-tools" ,clojure-tools)
    ("clj-kondo" ,clj-kondo)))
 (home-page "")
 (synopsis "")
 (description "")
 (license #f))
